#
# Containers and Images
# Check `README.md` for usage instructions.
#

version: '3.9'

services:

  mongodb:
    image: docker.io/mongo:7.0-jammy
    ports:
      - "27017:27017"

  main:
    image: ${registry:-}realworld:1.0
    labels:
      app: minitwit
      type: backend
    depends_on:
      - mongodb
    environment:
      mongodbUrl: mongodb://mongodb/hexagon_twitter_clone
    build:
      context: .
    ports:
      - "3090:9090"
