#
# Containers and Images
# Check `README.md` for usage instructions.
#

version: '3'

services:

  mongodb:
    image: mongo:4.2.0
    ports:
      - 27017:27017

  main:
    image: ${registry:-}realworld:1.0
    labels:
      app: minitwit
      type: backend
    depends_on:
      - mongodb
    environment:
      SERVICE_mongodbUrl: mongodb://mongodb/hexagon_twitter_clone
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3090:9090
