#
# Containers and Images
# Check `README.md` for usage instructions.
#

version: '3'

services:

  mongodb:
    image: mongo:4.2.0
    ports:
      - 3010:27017

  keycloak:
    image: jboss/keycloak:9.0.3
    environment:
      KEYCLOAK_USER: root
      KEYCLOAK_PASSWORD: root
    ports:
      - 3020:8080

  main:
    image: ${registry:-}realworld:1.0
    labels:
      app: minitwit
      type: backend
    depends_on:
      - mongodb
    environment:
      SERVICE_mongodbUrl: mongodb://mongodb/real_world
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - 3090:9090
