
serverName: TwitterClone

bindPort: 9090
bindAddress: 0.0.0.0
contextPath: /api

mongodbUrl: mongodb://localhost:27017/hexagon_twitter_clone

keyStoreResource: keystore.p12
keyStorePassword: storepass
keyPairAlias: twitterClone