
name: Main

on: [ push, pull_request ]

jobs:
  main:
    name: Main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          cache: gradle
      - name: Build & Test
        run: .github/pre-push.sh
